name: Deploy Linux

on:
  push:
    branches:
      - master  # Define a branch para ativar o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Linux
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /Desktop/prodEnv/PIM-ADS_4-semestre/pim_web
            git pull origin master
            # Adicione outros comandos necessários, como restart de serviço
